CREATE TABLE top_stories (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL
  url VARCHAR(250) NOT NULL
  score INT NOT NULL
  times VARCHAR(250) NOT NULL
  by_user VARCHAR(250) NOT NULL

);
